(in-package :magicffi)

(include-or "/usr/include/magic.h"
            "/usr/local/include/magic.h")

(progn
  (constant (+MAGIC-NONE+ "MAGIC_NONE")
    :documentation "No flags")
  (constant (+MAGIC-DEBUG+ "MAGIC_DEBUG")
    :documentation "Turn on debugging")
  (constant (+MAGIC-SYMLINK+ "MAGIC_SYMLINK")
    :documentation "Follow symlinks")
  (constant (+MAGIC-COMPRESS+ "MAGIC_COMPRESS")
    :documentation "Check inside compressed files")
  (constant (+MAGIC-DEVICES+ "MAGIC_DEVICES")
    :documentation "Look at the contents of devices")
  (constant (+MAGIC-MIME-TYPE+ "MAGIC_MIME_TYPE")
    :documentation "Return the MIME type")
  (constant (+MAGIC-CONTINUE+ "MAGIC_CONTINUE")
    :documentation "Return all matches")
  (constant (+MAGIC-CHECK+ "MAGIC_CHECK")
    :documentation "Print warnings to stderr")
  (constant (+MAGIC-PRESERVE-ATIME+ "MAGIC_PRESERVE_ATIME")
    :documentation "Restore access time on exit")
  (constant (+MAGIC-RAW+ "MAGIC_RAW")
    :documentation "Don't translate unprintable chars")
  (constant (+MAGIC-ERROR+ "MAGIC_ERROR")
    :documentation "Handle ENOENT etc as real errors")
  (constant (+MAGIC-MIME-ENCODING+ "MAGIC_MIME_ENCODING")
    :documentation "Return the MIME encoding")
  (constant (+MAGIC-MIME+ "MAGIC_MIME")
    :documentation NIL)
  (constant (+MAGIC-APPLE+ "MAGIC_APPLE")
    :documentation "Return the Apple creator and type")
  (constant (+MAGIC-NO-CHECK-COMPRESS+ "MAGIC_NO_CHECK_COMPRESS")
    :documentation "Don't check for compressed files")
  (constant (+MAGIC-NO-CHECK-TAR+ "MAGIC_NO_CHECK_TAR")
    :documentation "Don't check for tar files")
  (constant (+MAGIC-NO-CHECK-SOFT+ "MAGIC_NO_CHECK_SOFT")
    :documentation "Don't check magic entries")
  (constant (+MAGIC-NO-CHECK-APPTYPE+ "MAGIC_NO_CHECK_APPTYPE")
    :documentation "Don't check application type")
  (constant (+MAGIC-NO-CHECK-ELF+ "MAGIC_NO_CHECK_ELF")
    :documentation "Don't check for elf details")
  (constant (+MAGIC-NO-CHECK-TEXT+ "MAGIC_NO_CHECK_TEXT")
    :documentation "Don't check for text files")
  (constant (+MAGIC-NO-CHECK-CDF+ "MAGIC_NO_CHECK_CDF")
    :documentation "Don't check for cdf files")
  (constant (+MAGIC-NO-CHECK-TOKENS+ "MAGIC_NO_CHECK_TOKENS")
    :documentation "Don't check tokens")
  (constant (+MAGIC-NO-CHECK-ENCODING+ "MAGIC_NO_CHECK_ENCODING")
    :documentation "Don't check text encodings")
  (constant (+MAGIC-NO-CHECK-ASCII+ "MAGIC_NO_CHECK_ASCII")
    :documentation NIL)
  (constant (+MAGIC-NO-CHECK-FORTRAN+ "MAGIC_NO_CHECK_FORTRAN")
    :documentation "Don't check ascii/fortran")
  (constant (+MAGIC-NO-CHECK-TROFF+ "MAGIC_NO_CHECK_TROFF")
    :documentation "Don't check ascii/troff"))

(bitfield magic-flags
  ((:NONE "MAGIC_NONE")
   :documentation "No flags")
  ((:DEBUG "MAGIC_DEBUG")
   :documentation "Turn on debugging")
  ((:SYMLINK "MAGIC_SYMLINK")
   :documentation "Follow symlinks")
  ((:COMPRESS "MAGIC_COMPRESS")
   :documentation "Check inside compressed files")
  ((:DEVICES "MAGIC_DEVICES")
   :documentation "Look at the contents of devices")
  ((:MIME-TYPE "MAGIC_MIME_TYPE")
   :documentation "Return the MIME type")
  ((:CONTINUE "MAGIC_CONTINUE")
   :documentation "Return all matches")
  ((:CHECK "MAGIC_CHECK")
   :documentation "Print warnings to stderr")
  ((:PRESERVE-ATIME "MAGIC_PRESERVE_ATIME")
   :documentation "Restore access time on exit")
  ((:RAW "MAGIC_RAW")
   :documentation "Don't translate unprintable chars")
  ((:ERROR "MAGIC_ERROR")
   :documentation "Handle ENOENT etc as real errors")
  ((:MIME-ENCODING "MAGIC_MIME_ENCODING")
   :documentation "Return the MIME encoding")
  ((:MIME "MAGIC_MIME")
   :documentation NIL)
  ((:APPLE "MAGIC_APPLE")
   :documentation "Return the Apple creator and type")
  ((:NO-CHECK-COMPRESS "MAGIC_NO_CHECK_COMPRESS")
   :documentation "Don't check for compressed files")
  ((:NO-CHECK-TAR "MAGIC_NO_CHECK_TAR")
   :documentation "Don't check for tar files")
  ((:NO-CHECK-SOFT "MAGIC_NO_CHECK_SOFT")
   :documentation "Don't check magic entries")
  ((:NO-CHECK-APPTYPE "MAGIC_NO_CHECK_APPTYPE")
   :documentation "Don't check application type")
  ((:NO-CHECK-ELF "MAGIC_NO_CHECK_ELF")
   :documentation "Don't check for elf details")
  ((:NO-CHECK-TEXT "MAGIC_NO_CHECK_TEXT")
   :documentation "Don't check for text files")
  ((:NO-CHECK-CDF "MAGIC_NO_CHECK_CDF")
   :documentation "Don't check for cdf files")
  ((:NO-CHECK-TOKENS "MAGIC_NO_CHECK_TOKENS")
   :documentation "Don't check tokens")
  ((:NO-CHECK-ENCODING "MAGIC_NO_CHECK_ENCODING")
   :documentation "Don't check text encodings")
  ((:NO-CHECK-ASCII "MAGIC_NO_CHECK_ASCII")
   :documentation NIL)
  ((:NO-CHECK-FORTRAN "MAGIC_NO_CHECK_FORTRAN")
   :documentation "Don't check ascii/fortran")
  ((:NO-CHECK-TROFF "MAGIC_NO_CHECK_TROFF")
   :documentation "Don't check ascii/troff"))
